apiVersion: v1
kind: Namespace
metadata:
  name: youtube
  labels:
    name: youtube
---
apiVersion: v1
kind: Service
metadata:
  namespace: youtube
  name: postgres
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  namespace: youtube
  name: postgres_scraper
  labels:
    app: postgres
spec:
  restartPolicy: Always
  containers:
    - image: docker.io/guzmansalv/youtube_postgres
      imagePullPolicy: Always
      name: postgres
      ports:
        - containerPort: 5432
          name: postgres
    - image: docker.io/guzmansalv/dbase_channels
      imagePullPolicy: Always
      name: dbase_scraper
    - image: guzmansalv/youtube_scraper
      imagePullPolicy: Always
      name: youtube_scaper
