apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: postgres
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: postgres-scraper
spec:
  containers:
    - image: docker.io/guzmansalv/youtube_postgres
      name: postgres
      ports:
        - containerPort: 5432
          name: postgres
    - image: docker.io/guzmansalv/dbase_channels
      name: scraper
