apiVersion: v1
kind: Namespace
metadata:
  name: youtube
  labels:
    name: youtube
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: youtube-pv-volume
  namespace: youtube
  annotations:
    pv.beta.kubernetes.io/gid: "1234"
  labels:
    type: local
    name: youtube
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/data/db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtube-pv-claim
  labels:
    name: youtube
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  namespace: youtube
  name: postgres
  labels:
    name: youtube
spec:
  ports:
    - name: postgresql
      protocol: TCP
      port: 12345
      targetPort: 5432
  selector:
    app: postgres
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  namespace: youtube
  name: postgres-scraper
  labels:
    app: postgres
    name: youtube
spec:
  securityContext:
    fsGroup: 1234
    runAsUser: 0
  volumes:
    - name: youtube-pv-storage
      persistentVolumeClaim:
        claimName: youtube-pv-claim
  restartPolicy: Always
  containers:
    - image: docker.io/guzmansalv/youtube_postgres
      imagePullPolicy: Always
      name: postgres
      ports:
        - containerPort: 5432
          name: postgres
      volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: youtube-pv-storage
    - image: docker.io/guzmansalv/dbase_channels
      imagePullPolicy: Always
      name: dbase-scraper
    - image: guzmansalv/youtube_scraper
      imagePullPolicy: Always
      name: youtube-scaper

